name: sugarcane-rvi
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - geopandas
  - rasterio
  - xarray
  - dask
  - scikit-learn
  - statsmodels
  - matplotlib
  - plotly
  - streamlit
  - pyyaml
  - jupyterlab
  - pip
  - pip:
      - tensorflow>=2.15,<3
      - sentinelhub>=3.10,<4
